services:
  - type: web
    name: dayaar-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FALLBACK_GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY_2
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
