export enum CallProviderType {
  CALLYZER_SIM = 'CALLYZER_SIM',
}

export enum CallOrigin {
  WEB = 'WEB',
  ANDROID = 'ANDROID',
}

export enum CallAttemptStatus {
  INITIATING = 'INITIATING',
  DIALING = 'DIALING',
  COMPLETED = 'COMPLETED',
  NOT_CONNECTED = 'NOT_CONNECTED',
  BUSY = 'BUSY',
  NO_ANSWER = 'NO_ANSWER',
  MISSED = 'MISSED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  UNKNOWN = 'UNKNOWN',
}

export enum CallCommandStatus {
  QUEUED = 'QUEUED',
  DELIVERED = 'DELIVERED',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  DIALING = 'DIALING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
}

export enum CallEventType {
  CALL_ATTEMPT_CREATED = 'CALL_ATTEMPT_CREATED',
  CALL_COMMAND_CREATED = 'CALL_COMMAND_CREATED',
  CALL_COMMAND_DELIVERED = 'CALL_COMMAND_DELIVERED',
  DEVICE_ACKNOWLEDGED = 'DEVICE_ACKNOWLEDGED',
  DIALING_STARTED = 'DIALING_STARTED',
  CALL_ENDED = 'CALL_ENDED',
  CALLYZER_WEBHOOK_RECEIVED = 'CALLYZER_WEBHOOK_RECEIVED',
  CALLYZER_CALL_MATCHED = 'CALLYZER_CALL_MATCHED',
  CALLYZER_CALL_UNMATCHED = 'CALLYZER_CALL_UNMATCHED',
  CALLYZER_MATCH_COLLISION = 'CALLYZER_MATCH_COLLISION',
  RECORDING_ARCHIVE_STARTED = 'RECORDING_ARCHIVE_STARTED',
  RECORDING_ARCHIVED = 'RECORDING_ARCHIVED',
  RECORDING_FAILED = 'RECORDING_FAILED',
  RECORDING_PURGED = 'RECORDING_PURGED',
  DISPOSITION_RECORDED = 'DISPOSITION_RECORDED',
}

export enum RecordingStatus {
  PENDING = 'PENDING',
  ARCHIVING = 'ARCHIVING',
  ARCHIVED = 'ARCHIVED',
  NO_RECORDING = 'NO_RECORDING',
  PURGED = 'PURGED',
  FAILED = 'FAILED',
}

export enum CallSyncStatus {
  PENDING = 'PENDING',
  MATCHED = 'MATCHED',
  UNMATCHED = 'UNMATCHED',
  COLLISION = 'COLLISION',
}

export enum CallDisposition {
  HOT = 'HOT',
  WARM = 'WARM',
  COLD = 'COLD',
  NOT_INTERESTED = 'NOT_INTERESTED',
  FOLLOW_UP = 'FOLLOW_UP',
}

export enum ProviderCallType {
  OUTGOING = 'Outgoing',
  INCOMING = 'Incoming',
  MISSED = 'Missed',
  REJECTED = 'Rejected',
}
