export enum CallProviderType {
  ANDROID_SIM = 'ANDROID_SIM',
  EXOTEL = 'EXOTEL',
  SIP = 'SIP',
  WEBRTC = 'WEBRTC',
}

export enum CallAttemptStatus {
  INITIATING = 'INITIATING',
  DIALING = 'DIALING',
  CONNECTED = 'CONNECTED',
  NOT_CONNECTED = 'NOT_CONNECTED',
  BUSY = 'BUSY',
  NO_ANSWER = 'NO_ANSWER',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  UNKNOWN = 'UNKNOWN',
}

export enum CallCommandStatus {
  QUEUED = 'QUEUED',
  DELIVERED = 'DELIVERED',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  DIALING = 'DIALING',
  CONNECTED = 'CONNECTED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
}

export enum CallEventType {
  CALL_COMMAND_CREATED = 'CALL_COMMAND_CREATED',
  DEVICE_ACKNOWLEDGED = 'DEVICE_ACKNOWLEDGED',
  DIALING_STARTED = 'DIALING_STARTED',
  CALL_CONNECTED = 'CALL_CONNECTED',
  CALL_ENDED = 'CALL_ENDED',
  CALL_LOG_RECEIVED = 'CALL_LOG_RECEIVED',
  RECORDING_UPLOAD_STARTED = 'RECORDING_UPLOAD_STARTED',
  RECORDING_AVAILABLE = 'RECORDING_AVAILABLE',
  RECORDING_FAILED = 'RECORDING_FAILED',
}

export enum RecordingStatus {
  NONE = 'NONE',
  PENDING = 'PENDING',
  AVAILABLE = 'AVAILABLE',
  FAILED = 'FAILED',
}
