export enum VerificationStatus {
  PENDING_ASSIGNMENT = 'PENDING_ASSIGNMENT',
  ASSIGNED = 'ASSIGNED',
  COMPLETED = 'COMPLETED',
  REVIEW_REQUIRED = 'REVIEW_REQUIRED',
  CLOSED = 'CLOSED',
}

export enum MismatchSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum MismatchType {
  DISPOSITION_MISMATCH = 'DISPOSITION_MISMATCH',
  QUALIFICATION_MISMATCH = 'QUALIFICATION_MISMATCH',
  PHONE_UNREACHABLE_MISMATCH = 'PHONE_UNREACHABLE_MISMATCH',
}
